plugins:
  - protocol: http
    className: br.ufs.gothings.plugins.http.HttpPlugin
    type: client+server
    properties:
      server.port: 8080
  - protocol: mqtt
    className: br.ufs.gothings.plugins.mqtt.MqttPlugin
    type: client+server
    properties:
      server.port: 11883
  - protocol: coap
    className: br.ufs.gothings.plugins.coap.CoapPlugin
    type: client+server
    properties:
      server.port: 55683
